[package]
name = "gaddag-rust"
version = "0.1.0"
authors = ["Simon Chervenak <sarras305@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
itertools = "0.8.2"
array-init = "0.1.1"
petgraph = "0.4.13"
indicatif = "0.13.0"
azul = { git = "https://github.com/maps4print/azul" }
druid = { git = "https://github.com/xi-editor/druid" }