[package]
name = "gaddag-rust"
version = "0.1.0"
authors = ["Simon Chervenak <sarras305@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
itertools = "0.8.1"
array-init = "0.1.1"
daggy = "0.6.0"
petgraph = "0.4.13"
petgraph-graphml = "1.0.2"